apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: c020frxnq-python 
  janus-idp.io/tekton: c020frxnq-python
  backstage.io/kubernetes-id: c020frxnq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c020frxnq-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml