apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c020frxnq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c020frxnq-python 
  name: c020frxnq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c020frxnq-python 
